= Gogen

Gogen is a small an simple data generation tool

== Getting started

[source,shell]
----
go get -u github.com/ogama/gogen
----

Create a new file named `numbers.json` for example :
[source,json]
----
{
  "template": {
    "_type": "number"
  },
  "options": {
    "seed": "a seed",
    "amount": 10
  }
}
----

Run this command
[source,shell]
----
gogen -f numbers.json
----

Output
[source]
----
9
9
6
5
0
4
5
1
8
5
----

You can write more complex template to generate more complex data structure see link:samples/users.json[users.json]

== Documentation

Gogen is a template based data generator. You have to write a file in JSON format to describe your data.

Here is the JSON structure :

[source,json]
----
{
  "template" : {
    // the data structure to generate.
    // This property is mandatory
  },
  "options": {
    // this is where to place your global configuration
  }
}
----

.Default global options
|===
|Option|Description|Default value
|seed|The seed to use to force the randomness to be the same on each nebula call. If null, the randomness will be different on each call|nil
|amount|The amount of data to generate based on the specified template|1
|skip|Nebula generate data based on an index. By using a seed you can generate data on specific indices using the skip property. For example if you want to generate 10 datas starting at index 10 you have to set skip property to 10 and amount to 10. 10|0
|generation|Specify the type of generation to use possible values : "instant" or "interval"|{ type: "instant" }
|alias|The list of custom alias to use. There is some default alias to use described in the alias section|see alias section
|===

=== Generation types

The generation type specify how nebula generate data.
By default nebula generate the amount of requested data.
You can change this behaviour by changing the generation.type global option.

[source,json]
----
{
  "template": {
    // template
  },
  "options": {
    "generation": {
      "type": <other generation type>
    }
  }
}
----

.Instant generation
[source,json]
----
{
  "template": {
    // template
  },
  "options": {
    "amount": 10,
    "generation": {
      "type": "instant"
    }
  }
}
----

.Interval generation
[source,json]
----
{
  "template": {
    // template
  },
  "options": {
    "amount": 10,
    "generation": {
      "type": "interval",
      "options": {
        "interval": 2000 // generate one item every 2 seconds
      }
    }
  }
}
----

=== Types

To use a specific type generator just create a json object in the template and add the special field `_type` with the name of the type as value :

[source,json]
----
{
  "_type": "number",
  "options": {
    // specific type options see below
  }
}
----

==== Number

|===
|Option|Description|Allowed value|Default value
|bounds.min|The smallest number to generate.|number|0
|bounds.max|The maximum number to generate.|number|10
|decimal|The number precision for the decimal part of the number.|integer|0
|sequence.enable|Enable the sequence behaviour for this generator.|boolean|false
|sequence.cycle|If the sequence is enable, and if the sequence reach the `bounds.max` reset the sequence to `bounds.min` otherwise throw an error|boolean|true
|sequence.increment|If the sequence is enable, specify the amount to increment between generations|number|1
|===

Example :

[source,json]
----
{
  "_type": "number",
  "options": {
    "bounds": {
      "min": 100,
      "max": 200
    },
      "decimal": 2,
      "sequence": {
      "enable": true,
      "cycle": true,
      "increment": 0.1
    }
  }
}
----

==== String

|===
|Option|Description|Allowed value|Default value
|pattern|The regex pattern to use to generate the string.|A regex string|"[A-Z]{1}[A-Za-z]{10,25}"
|===

Example

[source,json]
----
{
  "template": {
    "_type": "string",
    "options": {
      "pattern": "[a-z]{10}"
    }
  },
  "options": {
    "seed": "test"
  }
}
----

==== Date

|===
|Option|Description|Allowed value|Default value
|bounds.min|The smallest date to generate.|yyyy-MM-ddTHH:mm:ss|1970-01-01T00:00:00
|bounds.max|The maximum date to generate.|yyyy-MM-ddTHH:mm:ss|2099-12-31T23:59:59
|truncate|The describe how to truncate the date|`milliseconds`, `seconds`, `minutes`, `hours`|`milliseconds`
|===

Example

[source,json]
----
{
  "template": {
    "_type": "date",
    "options": {
      "bounds": {
        "min": "2020-06-11T14:32:24",
        "max": "2020-06-11T14:32:24"
      },
      "truncate": "hours"
    }
  }
}
----

==== Array

|===
|Option|Description|Allowed value|Default value
|bounds.min|The minimum amount of items to generate.|number|0
|bounds.max|The maximum amount of items to generate.|number|10
|itemTemplate|The template of the item to generate|json object template|nil
|===

Example

[source,json]
----
{
  "template": {
    "_type": "array",
    "options": {
      "bounds": {
        "min": 10,
        "max": 10
      },
      "itemTemplate": {
        "_type": "number",
        "options": {
          "sequence": {
            "enable": true,
            "cycle": true,
            "increment": 1
          }
        }
      }
    }
  }
}
----

==== Picker

This type ramdomly pick an item among a given list

|===
|Option|Description|Allowed value|Default value
|items|The list of items to pick|A list of items : constant value or object or probabilistic item (see bellow)|nil
|===

Probabilistic item is an object with two properties :

* value : object or constant value
* probability : a decimal number between 0 and 100

The sum of all items must be equal to 100 otherwise an error will be return.

Example
----
{
  "template": {
    "_type": "picker",
    "options": {
      "items": [
        true,
        false
      ]
    }
  }
}
----

Example with probability
----
{
  "template": {
    "_type": "picker",
    "options": {
      "items": [
        {
          "value": true,
          "probability": 80
        },
        {
          "value": false,
          "probability": 20
        }
      ]
    }
  }
}
----

==== Ref

=== Alias

Alias allow to define type shortcut to simplify template an avoid duplicate

----
{
  "template": {
    "code": {
      "_type": "sha-256"
    }
  },
  "options": {
    "amount": 10,
    "alias": {
      "sha-256": {
        "template": {
          "_type": "string",
          "options": {
            "pattern": "[A-Z0-9]{64}"
          }
        }
      }
    }
  }
}
----

==== Custom aliases

==== Default aliases

=== File inclusion